#file: noinspection UndefinedParamsPresent
name: JIB container publish

on:
    release:
        types: [created]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: JIB container build and publish
              uses: MathieuSoysal/jib-container-publish.yml@v2.1.5
              with:
                  PASSWORD: ${{ secrets.JIB_DEPLOY_TOKEN }}
                  java-version: 21
                  module: 300-appl
                  mainClass: eu.oberon.oss.demos.reg.appl.UserRegistrationApplication
                  